### ISSUE TITLE
support underworld map

### ISSUE THREAD

**Issue by Foul-Tarnished** [Pear0533/ERMapGenerator#2]
I only got

`MENU_MapTile_M00_L0_00_00_00000000.tga`
`MENU_MapTile_M00_L1_00_00_00000000.tga`
`MENU_MapTile_M00_L2_00_00_00000000.tga`
`MENU_MapTile_M00_L3_00_00_00000000.tga`
`MENU_MapTile_M00_L4_00_00_00000000.tga`

and nothing for the underworld map.

Also, most people only care about the L0 one, as the others are just lower res.
Well some are more like cut-content/old WIP.

And doing all of them makes the process way slower

**Comment by Pear0533** [comment]
Feel free to implement support for underworld map generation. Unfortunately I do not have the time to make these changes, so it is in the best interest of community members to make these improvements themselves, as I have moved on to other projects.
